site:
  title: Self Driving Car - Internet of Things
  url: https://github.com/IakMastro/self-driving-car-docs
  start_page: self-driving-car_internet-of-things::index.adoc
content:
  sources:
  - url: https://github.com/IakMastro/self-driving-car-docs
    branches: master
    start_path: internet-of-things
ui:
  bundle:
    url: https://git.swarmlab.io:3000/docs/docs/raw/branch/master/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    :plantuml-server-url: http://www.plantuml.com/plantuml
  extensions:
  - '@djencks/asciidoctor-mathjax'
  - asciidoctor-plantuml